### ISSUE TITLE
Revolt and Divolt share the same package ID

### ISSUE THREAD

**Issue by ggtylerr** [ggtylerr/divolt-android#1]
Right now, the two apps share the same ID, causing the two to be uninstallable next to eachother.

The problem is, if we choose to change it, it'll require a refactor of all files under `app/src/main/java/...` and would make fetching upstream harder.

I'm labelling this issue as `wontfix` for now since not a lot of users use both, but if anyone has any suggestions, I'm open ears.

**Comment by taskylizard** [comment]
so true

**Comment by lunananananananana** [comment]
> it'll require a refactor of all files under app/src/main/java/...

This is false. All that would need to be changed is the two instances of the ID in [`build.gradle`](https://github.com/ggtylerr/divolt-android/blob/master/app/build.gradle); the Java package names are just a convention and can stay the same.

**Comment by ggtylerr** [comment]
> This is false. All that would need to be changed is the two instances of the ID in [`build.gradle`](https://github.com/ggtylerr/divolt-android/blob/master/app/build.gradle); the Java package names are just a convention and can stay the same.

I uh... did not know that. I'm sorry, I mainly code in JS / Web and haven't done Java in a long time, and even then I wasn't very good at it. 

[This is now implemented in Release v1.0.1,](https://github.com/ggtylerr/divolt-android/releases/tag/v1.0.1) thank you :)
