### ISSUE TITLE
F-droid 

### ISSUE THREAD

**Issue by z8512** [ggtylerr/divolt-android#2]
Since this app is free & open-source please add it on f-droid repo

**Comment by ggtylerr** [comment]
Doing this will require self hosting the repo, like with Revolt. Also not sure how it'd work alongside Revolt's repo.

I'm currently focusing on forking [RVMob](https://github.com/revoltchat/rvmob), but once that's done I'll look into it :)

**Comment by z8512** [comment]
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by ggtylerr** [comment]
This app uses Web Activities, which relies on Google. AFAIK they don't accept apps like that (and it's why Revolt is also doing the same thing.)

I'm trying to setup a repo right now but it does *not* want to cooperate with me :(
![image](https://user-images.githubusercontent.com/28498877/169717349-6566bb43-be3d-4c30-88dd-9b5c03d0dcb8.png)

**Comment by ggtylerr** [comment]
Update: After moving to a new server it appears to be working with me now - repo is available at [fdroid.ggtyler.dev.](https://fdroid.ggtyler.dev) Sorry for the long wait.
